global:
  scrape_interval:     15s # Define o intervalo de coleta para 15 segundos.
  evaluation_interval: 15s # O intervalo de avaliação controla com que frequência as regras de alerta são avaliadas.

scrape_configs:
  - job_name: 'prometheus' # Define um trabalho chamado 'prometheus'.
    static_configs:
      - targets: ['localhost:9090'] # O Prometheus coleta métricas de si mesmo em localhost na porta 9090.

  - job_name: 'spring_app' # Define um trabalho para a aplicação Spring Boot.
    metrics_path: '/actuator/prometheus' # O caminho para as métricas expostas pela aplicação Spring Boot.
    scrape_interval: 5s # Define um intervalo de coleta específico para essa aplicação.
    static_configs:
      - targets: ['spring_app_host:8080'] # Substitua 'spring_app_host' pelo hostname ou IP da sua aplicação Spring Boot.